import { Inter } from 'next/font/google';
import React from 'react';
import Navbar from '@/components/Navbar';
import './globals.css';
import { Toaster } from 'react-hot-toast';

// const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface Props {
  children: React.ReactNode;
}

const RootLayout: React.FC<Props> = ({ children }) => {
  return (
    <html lang="en">
      <body className="mt-14">
        <Toaster toastOptions={{ duration: 4000 }} />
        <Navbar />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
